import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/Theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Theme.colors.background },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { minHeight: 76, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: Theme.colors.border },
  eyebrow: { color: Theme.colors.greenDark, fontWeight: '900', fontSize: 11 },
  greeting: { color: Theme.colors.ink, fontWeight: '900', fontSize: 19, marginTop: 2 },
  content: { padding: 16, paddingBottom: 48, maxWidth: 720, width: '100%', alignSelf: 'center' },
  goalBand: { minHeight: 70, flexDirection: 'row', alignItems: 'center', backgroundColor: '#EAF7FE', borderWidth: 1, borderColor: '#CBEAFA', borderRadius: 8, padding: 12, gap: 10, marginBottom: 14 },
  goalIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  goalCopy: { flex: 1 },
  goalTitle: { color: Theme.colors.ink, fontWeight: '800', fontSize: 14, marginBottom: 7 },
  goalValue: { color: Theme.colors.blueDark, fontWeight: '900', fontSize: 13 },
  progressTrack: { height: 9, borderRadius: 5, backgroundColor: '#C9DFEA', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: Theme.colors.blue },
  levelTabs: { flexDirection: 'row', gap: 8, marginBottom: 13 },
  levelTab: { flex: 1, minWidth: 0, minHeight: 76, alignItems: 'center', justifyContent: 'center', gap: 3, padding: 7, borderWidth: 2, borderBottomWidth: 4, borderColor: Theme.colors.border, borderRadius: 8, backgroundColor: '#FFFFFF' },
  levelTabActive: { borderColor: Theme.colors.green, backgroundColor: '#F0FBF2' },
  levelBadge: { width: 29, height: 29, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  levelBadgeOpen: { backgroundColor: Theme.colors.green },
  levelBadgeLocked: { backgroundColor: '#E8EEF2' },
  levelTabTitle: { color: Theme.colors.ink, fontSize: 12, fontWeight: '900' },
  levelTabTitleActive: { color: Theme.colors.greenDark },
  levelTabProgress: { color: Theme.colors.muted, fontSize: 10, fontWeight: '800' },
  levelOverview: { paddingVertical: 10, marginBottom: 9 },
  levelLabel: { color: Theme.colors.greenDark, fontSize: 11, fontWeight: '900' },
  levelTitle: { color: Theme.colors.ink, fontSize: 21, lineHeight: 27, fontWeight: '900', marginTop: 2 },
  levelStats: { color: Theme.colors.muted, fontSize: 13, fontWeight: '700', marginTop: 5 },
  unitSection: { marginBottom: 12 },
  unitHeader: { minHeight: 104, borderRadius: 8, borderBottomWidth: 4, borderBottomColor: Theme.colors.greenDark, backgroundColor: Theme.colors.green, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, overflow: 'hidden' },
  unitPressed: { opacity: 0.9, transform: [{ translateY: 1 }] },
  unitImage: { position: 'absolute', right: 0, top: 0, width: '48%', height: '100%' },
  unitImageShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(28,45,52,0.36)' },
  unitState: { width: 42, height: 42, borderRadius: 21, backgroundColor: Theme.colors.blue, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: 'rgba(255,255,255,0.9)' },
  unitStateComplete: { backgroundColor: Theme.colors.greenDark },
  unitStateLocked: { backgroundColor: 'rgba(255,255,255,0.9)' },
  unitCopy: { flex: 1, minWidth: 0 },
  unitEyebrow: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },
  unitTitle: { color: '#FFFFFF', fontSize: 19, fontWeight: '900', marginTop: 2 },
  unitSubtitle: { color: '#FFFFFF', fontSize: 12, lineHeight: 17, fontWeight: '700', marginTop: 3, maxWidth: 360 },
  chevron: { width: 34, height: 42, alignItems: 'center', justifyContent: 'center' },
  path: { paddingTop: 14, paddingBottom: 4 },
  errorBand: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderWidth: 1, borderColor: '#FFD0CD', borderRadius: 8, backgroundColor: '#FFF0EF', marginBottom: 16 },
  errorText: { flex: 1, color: Theme.colors.coralDark, fontWeight: '700', lineHeight: 19 },
  retryButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
});
