import { Theme } from '@/constants/Theme';

export const exploreStyles: any = {
  safe: { flex: 1, backgroundColor: '#F8F9FA' },
  header: {
    paddingHorizontal: 22,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: Theme.colors.ink,
  },
  content: {
    padding: 22,
    paddingBottom: 40,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Theme.colors.ink,
    marginBottom: 16,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
    borderColor: Theme.colors.green,
  },
  cardImageContainer: {
    height: 160,
    backgroundColor: '#EAF7FE',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  badge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: Theme.colors.coral,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  cardContent: {
    padding: 20,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: Theme.colors.ink,
    marginBottom: 8,
  },
  cardDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: Theme.colors.muted,
    marginBottom: 20,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  actionText: {
    fontSize: 16,
    fontWeight: '800',
    color: Theme.colors.greenDark,
  },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, backgroundColor: '#FFF', borderRadius: 16, borderWidth: 1, borderColor: Theme.colors.border, borderStyle: 'dashed' },
  emptyStateText: { fontSize: 16, fontWeight: '800', color: Theme.colors.ink, marginTop: 15 },
  emptyStateSubtext: { fontSize: 13, color: Theme.colors.muted, marginTop: 5 },
  logList: { gap: 15 },
  logCard: { backgroundColor: '#FFF', borderRadius: 16, borderWidth: 1, borderColor: Theme.colors.border, overflow: 'hidden' },
  logImage: { width: '100%', aspectRatio: 4 / 3, backgroundColor: '#E8EEF2' },
  logCardContent: { padding: 15 },
  logCaption: { fontSize: 18, fontWeight: '900', color: Theme.colors.ink, lineHeight: 24, marginBottom: 12 },
  vocabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 15 },
  vocabBadge: { backgroundColor: '#F0EDFF', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 15 },
  vocabBadgeText: { color: Theme.colors.violet, fontWeight: '800', fontSize: 12 },
  listenBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#EAF7FE', alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 },
  listenBtnText: { color: Theme.colors.blueDark, fontWeight: '800', fontSize: 13 }
};
