import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/Theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Theme.colors.background },
  content: { width: '100%', maxWidth: 1180, alignSelf: 'center', padding: 18, paddingBottom: 54 },
  heading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 14 },
  headingCopy: { flex: 1, minWidth: 240 },
  eyebrow: { color: Theme.colors.greenDark, fontSize: 11, fontWeight: '900' },
  title: { color: Theme.colors.ink, fontSize: 28, fontWeight: '900', marginTop: 3 },
  subtitle: { color: Theme.colors.muted, marginTop: 4 },
  headingActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  levelTabs: { flexDirection: 'row', gap: 8, marginTop: 20 },
  levelTab: { flex: 1, minWidth: 0, minHeight: 76, borderWidth: 2, borderBottomWidth: 4, borderColor: Theme.colors.border, borderRadius: 8, backgroundColor: '#FFFFFF', padding: 10, justifyContent: 'center' },
  levelDot: { width: 20, height: 5, borderRadius: 3, marginBottom: 6 },
  levelName: { color: Theme.colors.ink, fontSize: 14, fontWeight: '900' },
  levelMeta: { color: Theme.colors.muted, fontSize: 10, marginTop: 3 },
  errorBand: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 14, borderWidth: 1, borderColor: '#FFD0CD', borderRadius: 8, backgroundColor: '#FFF0EF', padding: 11 },
  errorText: { flex: 1, color: Theme.colors.coralDark, fontWeight: '700' },
  loading: { minHeight: 360, alignItems: 'center', justifyContent: 'center' },
  versionBar: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10, marginTop: 16 },
  versionList: { gap: 8, flexGrow: 1, minWidth: 220 },
  versionChip: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 7, backgroundColor: '#FFFFFF', paddingHorizontal: 10 },
  versionChipActive: { borderColor: Theme.colors.blue, backgroundColor: '#EEF8FE' },
  versionCode: { color: Theme.colors.ink, fontSize: 11, fontWeight: '900' },
  versionHeader: { minHeight: 86, marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: 1, borderBottomWidth: 1, borderColor: Theme.colors.border, paddingVertical: 12 },
  versionCopy: { flex: 1 },
  versionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  versionTitle: { color: Theme.colors.ink, fontSize: 20, fontWeight: '900' },
  versionDescription: { color: Theme.colors.muted, lineHeight: 19, marginTop: 4 },
  versionActions: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap', justifyContent: 'flex-end' },
  sectionHeading: { minHeight: 70, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 10 },
  sectionTitle: { color: Theme.colors.ink, fontSize: 18, fontWeight: '900' },
  sectionMeta: { color: Theme.colors.muted, fontSize: 11, marginTop: 2 },
  tree: { gap: 10 },
  unitSection: { borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 8, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  unitHeader: { minHeight: 76, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10, padding: 11, backgroundColor: '#F8FBFC' },
  orderBadge: { width: 40, height: 40, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E7F8EA' },
  orderText: { color: Theme.colors.greenDark, fontSize: 17, fontWeight: '900' },
  rowCopy: { flex: 1, minWidth: 0 },
  unitTitle: { color: Theme.colors.ink, fontSize: 17, fontWeight: '900' },
  rowMeta: { color: Theme.colors.muted, fontSize: 10, marginTop: 3 },
  rowTools: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', flexWrap: 'wrap', maxWidth: 144 },
  unitBody: { borderTopWidth: 1, borderTopColor: Theme.colors.border },
  unitDescriptionRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 13 },
  unitDescription: { flex: 1, color: Theme.colors.muted, lineHeight: 18 },
  lessonSection: { borderTopWidth: 1, borderTopColor: Theme.colors.border },
  lessonRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 9, padding: 10 },
  lessonOrder: { width: 28, height: 28, borderRadius: 6, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EAF7FE' },
  lessonOrderText: { color: Theme.colors.blueDark, fontWeight: '900', fontSize: 11 },
  lessonTitle: { color: Theme.colors.ink, fontWeight: '900' },
  activityArea: { backgroundColor: '#F8FAFB', paddingBottom: 8 },
  activityAreaHeader: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14 },
  objective: { flex: 1, color: Theme.colors.muted, fontSize: 12, lineHeight: 17 },
  activityRow: { minHeight: 62, marginHorizontal: 10, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, borderTopWidth: 1, borderTopColor: Theme.colors.border, paddingVertical: 7 },
  activityIcon: { width: 34, height: 34, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0EDFF' },
  activityTitle: { color: Theme.colors.ink, fontWeight: '800', fontSize: 12 },
  command: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1, borderBottomWidth: 3, borderColor: Theme.colors.border, borderRadius: 7, backgroundColor: '#FFFFFF', paddingHorizontal: 12 },
  commandSmall: { minHeight: 38, borderBottomWidth: 2, paddingHorizontal: 9 },
  commandPrimary: { borderColor: Theme.colors.greenDark, backgroundColor: Theme.colors.green },
  commandDanger: { borderColor: '#F1B8B4', backgroundColor: '#FFF4F3' },
  commandText: { color: Theme.colors.ink, fontSize: 12, fontWeight: '900' },
  commandTextPrimary: { color: '#FFFFFF' },
  commandTextDanger: { color: Theme.colors.coralDark },
  iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 7 },
  iconButtonCompact: { width: 34, height: 34 },
  iconTouch: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  disabled: { opacity: 0.32 },
  statusBadge: { borderRadius: 5, paddingHorizontal: 7, paddingVertical: 4 },
  statusDraft: { backgroundColor: '#FFF5CE' },
  statusPublished: { backgroundColor: '#E6F8E9' },
  statusArchived: { backgroundColor: '#EDF2F5' },
  statusText: { fontSize: 8, fontWeight: '900' },
  statusDraftText: { color: Theme.colors.yellowDark },
  statusPublishedText: { color: Theme.colors.greenDark },
  statusArchivedText: { color: Theme.colors.muted },
  validation: { marginTop: 12, borderWidth: 1, borderRadius: 8, padding: 12 },
  validationSuccess: { borderColor: '#BFE8C5', backgroundColor: '#F0FBF2' },
  validationError: { borderColor: '#FFD0CD', backgroundColor: '#FFF5F4' },
  validationHeader: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 8 },
  validationTitle: { flex: 1, color: Theme.colors.ink, fontWeight: '900' },
  issueRow: { borderTopWidth: 1, borderTopColor: 'rgba(113,128,140,0.18)', paddingVertical: 7 },
  issuePath: { color: Theme.colors.coralDark, fontSize: 10, fontWeight: '900' },
  issueMessage: { color: Theme.colors.ink, fontSize: 12, marginTop: 2 },
  empty: { minHeight: 300, alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { color: Theme.colors.ink, fontSize: 18, fontWeight: '900', marginTop: 10 },
  modalSafe: { flex: 1, backgroundColor: 'rgba(25,39,47,0.55)' },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', alignItems: 'center' },
  modalPanel: { width: '100%', maxWidth: 680, maxHeight: '92%', borderTopLeftRadius: 8, borderTopRightRadius: 8, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  modalWide: { maxWidth: 850 },
  modalHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: Theme.colors.border, paddingHorizontal: 16 },
  modalTitle: { flex: 1, color: Theme.colors.ink, fontSize: 19, fontWeight: '900' },
  modalContent: { padding: 16, paddingBottom: 28, gap: 14 },
  confirmSafe: { flex: 1, backgroundColor: 'rgba(25,39,47,0.55)' },
  confirmBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 18 },
  confirmPanel: { width: '100%', maxWidth: 440, borderRadius: 8, backgroundColor: '#FFFFFF', padding: 20, alignItems: 'center' },
  confirmIcon: { width: 52, height: 52, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EAF7FE' },
  confirmIconDanger: { backgroundColor: '#FFF0EF' },
  confirmTitle: { color: Theme.colors.ink, fontSize: 20, fontWeight: '900', textAlign: 'center', marginTop: 13 },
  confirmMessage: { color: Theme.colors.muted, lineHeight: 20, textAlign: 'center', marginTop: 8 },
  confirmActions: { width: '100%', flexDirection: 'row', justifyContent: 'center', gap: 9, marginTop: 18 },
  field: { gap: 5 },
  fieldLabel: { color: Theme.colors.ink, fontSize: 12, fontWeight: '900' },
  fieldHint: { color: Theme.colors.muted, fontSize: 10, lineHeight: 15 },
  fieldError: { color: Theme.colors.coralDark, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  input: { minHeight: 50, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 7, backgroundColor: '#FFFFFF', paddingHorizontal: 12, color: Theme.colors.ink, fontSize: 15 },
  inputError: { borderColor: Theme.colors.coralDark, backgroundColor: '#FFF9F8' },
  multiline: { minHeight: 92, paddingTop: 12 },
  twoColumns: { flexDirection: 'row', gap: 10 },
  fieldColumn: { flex: 1 },
  mediaFields: { gap: 10, borderTopWidth: 1, borderTopColor: Theme.colors.border, paddingTop: 13 },
  groupTitle: { color: Theme.colors.greenDark, fontWeight: '900', fontSize: 13 },
  typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  typeOption: { width: '31%', minWidth: 105, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 4, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 7, backgroundColor: '#FFFFFF', padding: 7 },
  typeOptionActive: { borderColor: Theme.colors.violet, backgroundColor: '#F2EFFF' },
  typeLabel: { color: Theme.colors.muted, fontSize: 10, fontWeight: '800', textAlign: 'center' },
  typeLabelActive: { color: Theme.colors.violet, fontWeight: '900' },
  segmented: { minHeight: 44, flexDirection: 'row', borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 7, overflow: 'hidden' },
  segment: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  segmentActive: { backgroundColor: '#EAF7FE' },
  segmentText: { color: Theme.colors.muted, fontSize: 11, fontWeight: '800' },
  segmentTextActive: { color: Theme.colors.blueDark, fontWeight: '900' },
  previewFrame: { gap: 12, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 8, backgroundColor: Theme.colors.background, padding: 15 },
  previewPrompt: { color: Theme.colors.ink, fontSize: 20, fontWeight: '900', textAlign: 'center' },
  previewInstruction: { color: Theme.colors.muted, textAlign: 'center', lineHeight: 19 },
  deleteWarning: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, borderWidth: 1, borderColor: '#FFD0CD', borderRadius: 8, backgroundColor: '#FFF4F3', padding: 12 },
  deleteWarningTitle: { color: Theme.colors.coralDark, fontWeight: '900' },
  deleteWarningText: { color: Theme.colors.ink, lineHeight: 19, marginTop: 3 },
});
